const places={airport:{name:"长春龙嘉机场",lat:43.996,lng:125.685},shenyangAirport:{name:"沈阳桃仙机场",lat:41.64,lng:123.483},carRental:{name:"一嗨租车 · 长春龙嘉机场店",lat:43.9956,lng:125.687},changchun:{name:"长春",lat:43.817,lng:125.324},lushuihe:{name:"露水河镇",lat:42.515,lng:127.795},luyuanHotel:{name:"抚松露源宾馆",lat:42.515,lng:127.795},hunting:{name:"露水河国际狩猎场",lat:42.533,lng:127.805},naitou:{name:"奶头山村",lat:42.45,lng:127.82},huamei:{name:"华美胜地",lat:42.115,lng:127.51},shuxinHotel:{name:"舒心民宿",lat:41.959381,lng:127.582842},south:{name:"长白山南坡",lat:41.997,lng:127.936},changbai:{name:"长白县",lat:41.42,lng:128.2},linjiang:{name:"临江",lat:41.811,lng:126.918},baishan:{name:"白山",lat:41.94,lng:126.414},shanshuiHotel:{name:"善水源休闲宾馆",lat:41.94,lng:126.414},huashan:{name:"花山溪谷",lat:41.75,lng:126.82},sihai:{name:"四海龙湾",lat:42.29,lng:126.45},bali:{name:"八里甸子",lat:41.18,lng:125.38},luyuanInn:{name:"鹿园客栈",lat:41.18,lng:125.38},dadi:{name:"大地森林公园",lat:41.15,lng:125.33},yanghu:{name:"洋湖沟",lat:41.07,lng:125.38},laobian:{name:"老边沟",lat:41.08,lng:124.94},dashi:{name:"大石湖",lat:41.11,lng:124.91},shenyang:{name:"沈阳",lat:41.806,lng:123.432}};
const airports={CSX:{name:"长沙黄花机场",lat:28.189,lng:113.22},HGH:{name:"杭州萧山机场",lat:30.237,lng:120.429},CGQ:{name:"长春龙嘉机场",lat:43.996,lng:125.685},SHE:{name:"沈阳桃仙机场",lat:41.64,lng:123.483}};
const flights=[{group:"父母",direction:"去程 · 10 月 1 日",flightNo:"FM7246",airline:"上海航空",duration:"3 小时 25 分",price:{amount:120,basis:"每人票价"},from:{code:"CSX",city:"长沙 T2",time:"11:30"},to:{code:"CGQ",city:"长春 T2",time:"14:55"},note:"父母从长沙出发；抵达后与东嵎、Sunny 会合。"},{group:"父母",direction:"回程 · 10 月 7 日",flightNo:"KY3032",airline:"昆明航空",duration:"3 小时 25 分",price:{amount:586,basis:"每人票价",breakdown:"¥466 + ¥120"},from:{code:"SHE",city:"沈阳桃仙 T3",time:"12:05"},to:{code:"CSX",city:"长沙 T3",time:"15:30"},note:"父母从沈阳桃仙机场返回长沙；航站楼与执飞计划请在出发前再次确认。"},{group:"东嵎、Sunny",direction:"去程 · 10 月 1 日",flightNo:"JD5395",airline:"首都航空",duration:"2 小时 55 分",price:{amount:319,basis:"每人票价",breakdown:"¥199 + ¥120"},from:{code:"HGH",city:"杭州 T3",time:"06:40"},to:{code:"CGQ",city:"长春 T2",time:"09:35"},note:"东嵎、Sunny 从杭州出发；上午先抵达长春。"},{group:"东嵎、Sunny",direction:"回程 · 10 月 7 日",flightNo:"HU7488",airline:"海南航空",duration:"2 小时 55 分",price:{amount:319,basis:"每人票价",breakdown:"¥199 + ¥120"},from:{code:"CGQ",city:"长春 T2",time:"20:00"},to:{code:"HGH",city:"杭州 T3",time:"22:55"},note:"需从沈阳返回长春龙嘉机场；目前 20:00 还车与 20:00 起飞无法衔接。"}];
const travelerGroups=[{group:"父母",origin:"长沙往返",travelers:2},{group:"东嵎、Sunny",origin:"杭州往返",travelers:2}];
const calendar=[{date:1,weekday:"周四",note:"抵达长春"},{date:2,weekday:"周五",note:"露水河"},{date:3,weekday:"周六",note:"G331"},{date:4,weekday:"周日",note:"双景区"},{date:5,weekday:"周一",note:"桓仁赏枫"},{date:6,weekday:"周二",note:"前往沈阳"},{date:7,weekday:"周三",note:"分组返程"}];
const carRental={provider:"一嗨租车",status:"预约成功 · 已支付",vehicle:"大众探歌",specs:["自动挡","SUV","1.4T","5 座","支持自助取还"],duration:"6 天 11 小时",place:"carRental",pickup:{date:"10 月 1 日",time:"09:00",store:"长春龙嘉机场店",location:"龙嘉国际机场地库 B2 层"},returnTrip:{date:"10 月 7 日",time:"20:00",store:"长春龙嘉机场店",location:"龙嘉国际机场地库 B2 层"},price:{total:"2,516.20",breakdown:[{label:"车辆租赁及门店服务",amount:"1,651"},{label:"基本保障 · 含小伤免赔",amount:"350"},{label:"其他服务",amount:"854.20"},{label:"车型升级会员优惠",amount:"-339"}]},warning:"原店还车时间与 HU7488 计划起飞时间同为 20:00，且和“辽出 / 沈阳落点”冲突；必须提前调整还车地点、时间或返程方案。"};
const days=[
{date:"10/1 周四",title:"长春 → 露水河镇",drive:"约 300 km",route:["airport","changchun","lushuihe"],activities:["东嵎、Sunny 从杭州出发，09:35 抵达长春；一嗨订单 09:00 起可在机场地库 B2 取车","父母从长沙出发，14:55 抵达长春；四人在长春会合","采购物资后前往露水河，预留国庆拥堵时间"],stay:"抚松露源宾馆"},
{date:"10/2 周五",title:"露水河 → 奶头山村 → 华美胜地",drive:"景区 + 轻徒步",route:["lushuihe","hunting","naitou","huamei"],activities:["露水河漂流、森林与鹿苑，先问喂鹿时间","奶头山村轻徒步 1–2 小时","胜地桥与漫江大峡谷，确认非住客通行"],stay:"舒心民宿"},
{date:"10/3 周六",title:"华美胜地 → 长白县 → 临江 → 白山",drive:"G331 长途日",route:["huamei","south","changbai","linjiang","baishan"],activities:["南坡提前预约，遇风雪停运立即切换方案","沿 G331 与鸭绿江边境公路南下","经临江抵达白山，不摸黑赶山路"],stay:"善水源休闲宾馆"},
{date:"10/4 周日",title:"白山 → 花山溪谷 → 四海龙湾 → 八里甸子",drive:"早起赏枫",route:["baishan","huashan","sihai","bali"],activities:["6:30 出发，花山溪谷尽量 8:00 前入园","四海龙湾预留 2.5–3 小时","驼靖线仅在天色、路况允许时加入"],stay:"鹿园客栈"},
{date:"10/5 周一",title:"大地森林公园 / 洋湖沟",drive:"近郊徒步",route:["bali","dadi","yanghu","bali"],activities:["大地森林公园尽量早到","洋湖沟体验相近，按父母体力二选一","返回同一住宿点"],stay:"鹿园客栈"},
{date:"10/6 周二",title:"桓仁 → 沈阳",drive:"转场日",route:["bali","laobian","dashi","shenyang"],activities:["原表无景点，可直接去沈阳","老边沟 + 大石湖仅作备选","车辆订单要求次日回长春龙嘉机场原店还车；沈阳住宿、停车及回长春安排待核"],stay:"沈阳 · 待补"},
{date:"10/7 周三",title:"沈阳 / 长春 → 分组返程",drive:"两组分流 · 还车待调整",route:["shenyang","shenyangAirport","airport"],activities:["父母从沈阳桃仙机场返程：KY3032，12:05 起飞，建议预留节假日值机与市区接驳时间","东嵎、Sunny 驾车返回长春龙嘉机场，乘 HU7488 于 20:00 起飞","一嗨订单同为 20:00 原店还车，无法衔接航班；需提前调整还车时间或门店"],stay:"回家"}];
const lodgings=[
{name:"抚松露源宾馆",city:"抚松 · 露水河镇",dates:"10 月 1–2 日",nights:"1 晚",place:"luyuanHotel",room:"普通标准间 · 2 间 · 无早餐",checkTimes:"10/1 06:00 后入住 · 10/2 14:00 前离店",note:"订单已确认；适合两组会合后的首晚休整。",price:{status:"booked",amount:"393.30",basis:"1 晚 · 2 间总价",source:"去哪儿订单截图"},bookingLinks:[{provider:"Trip.com",url:"https://www.trip.com/hotels/fusong-hotel-detail-63631650/luyuan-hotel/"}]},
{name:"舒心民宿",city:"抚松 · 池南区附近",dates:"10 月 2–3 日",nights:"1 晚",place:"shuxinHotel",room:"套房 · 1 间 · 可住 4 人 · 无早餐",checkTimes:"10/2 14:00 后入住 · 10/3 12:00 前离店",note:"约 70–80㎡，适合四人同住；位于华美胜地与南坡行程之间。",price:{status:"booked",amount:"249.48",basis:"1 晚总价",source:"去哪儿订单截图"},bookingLinks:[{provider:"携程",url:"https://m.ctrip.com/html5/hotel/hoteldetail/123074668.html"}]},
{name:"善水源休闲宾馆",city:"白山 · 浑江区",dates:"10 月 3–4 日",nights:"1 晚",place:"shanshuiHotel",room:"标准大床房 · 2 间 · 每间 2 份早餐",checkTimes:"10/3 14:00 后入住 · 10/4 13:00 前离店",note:"订单已确认；第二天早起前往花山溪谷。",price:{status:"booked",amount:"270",basis:"1 晚 · 2 间总价",source:"美团订单截图"},bookingLinks:[]},
{name:"鹿园客栈",city:"桓仁 · 八里甸子镇",dates:"10 月 4–6 日",nights:"2 晚",place:"luyuanInn",room:"每晚 2 间 · 无餐食",checkTimes:"10/4 12:00 后入住 · 10/6 12:00 前离店",note:"10/4：兰韵 2 间 ¥344；10/5：菊韵 1 间 ¥147 + 兰韵 1 间 ¥169。",price:{status:"booked",amount:"660",basis:"2 晚 · 4 间夜总价",source:"去哪儿 3 笔订单截图"},bookingLinks:[]},
{name:"沈阳住宿 · 待补",city:"沈阳",dates:"10 月 6 日",nights:"1 晚",place:"shenyang",room:"待补",checkTimes:"待补",note:"原文未提供 10 月 6 日住宿订单。",price:null,bookingLinks:[]}
];
const spots=[{name:"露水河国际狩猎场",tag:"漂流 · 喂鹿 · 森林",place:"hunting",note:"建议 4–5 小时；先确认漂流、鹿苑开放及老人年龄限制。",image:"https://cdn.nlark.com/yuque/0/2026/png/21411456/1786248400562-2a944a68-82dc-4553-abf6-4911c1e19d7e.png"},{name:"奶头山村轻徒步",tag:"乡村 · 1–2 小时",place:"naitou",note:"过桥后停车，沿步道择一段往返；服从防火管理。",image:"https://cdn.nlark.com/yuque/0/2026/png/21411456/1786244461734-cac8dd6e-40c8-4e23-a40f-400b5b544ff0.png"},{name:"华美胜地",tag:"峡谷 · 轻徒步",place:"huamei",note:"胜地桥—漫江大峡谷 1.5–2.5 小时；确认非住客通行。",image:"https://cdn.nlark.com/yuque/0/2026/png/21411456/1786757315949-7d8df13b-0a97-4bd7-84bc-32b654ee1647.png"},{name:"长白山南坡",tag:"天池 · 预约",place:"south",note:"成人票+环保车参考 190 元；国庆前复核开放和维修状态。"},{name:"花山溪谷",tag:"枫叶谷 · 早到",place:"huashan",note:"建议 3–5 小时，国庆 8:00 前入园。",image:"https://cdn.nlark.com/yuque/0/2026/png/21411456/1786758378795-803aff0c-1be8-47c9-9d89-39fe51a27f08.png"},{name:"四海龙湾",tag:"玛珥湖 · 环湖",place:"sihai",note:"瞭望塔是核心机位；沿途补给少。",image:"https://cdn.nlark.com/yuque/0/2026/png/21411456/1786250299983-92e72467-3467-4e4d-bb68-7889caf91882.png"},{name:"大地森林公园",tag:"沿溪 · 瀑布",place:"dadi",note:"道路窄，国庆早到。",image:"https://cdn.nlark.com/yuque/0/2026/png/21411456/1786762750541-f12af043-f826-4aab-88c7-c1b10921948a.png"},{name:"洋湖沟",tag:"免费参考 · 沿溪",place:"yanghu",note:"与大地森林公园相似，体力不足二选一。",image:"https://cdn.nlark.com/yuque/0/2026/png/21411456/1786762332257-f3cf4753-0680-4800-9d83-f6bf81c0c9ca.png"}];
const driving=[{name:"G331 长白县段",tag:"10/3 主线",note:"提前加油并下载离线地图。"},{name:"驼靖线",tag:"10/4 视路况",note:"山区天黑早，仅在道路开放、天气稳定时加入。"},{name:"本桓 / 本恒公路",tag:"命名待核",note:"原文写“本恒公路”，常见称呼为本桓公路；严禁弯道停车。"},{name:"老边沟 + 大石湖",tag:"10/6 备选",note:"不影响沈阳转场和次日回长春还车时再增加。"}];
const prep=[{group:"原文必备",items:["雨衣、漂流手机防水袋、替换衣物","野餐/露营设备；林区严格防火","提前从可靠平台预订景区票"]},{group:"车辆与驾驶",items:["取车时核对大众探歌车况、油量、轮胎、备胎与保障范围","确认自助取还流程，提前拍摄车辆和停车位置","下载离线地图，山区提前加油"]},{group:"衣物与徒步",items:["速干层、抓绒、薄羽绒、防风雨层","防滑鞋、备用袜、登山杖与常用药","连续徒步按父母体力做减法"]},{group:"必须补齐",items:["调整一嗨龙嘉机场 10/7 20:00 的还车时间或地点","确认 KY3032 长沙到达航站楼及 10/7 执飞计划","安排父母从沈阳市区前往桃仙机场的接驳","补齐 10 月 6 日沈阳住宿"]}];
const colors=["#a84631","#c77728","#1f6b55","#35778c","#66558f","#8b6b2b","#315f76"];
function priceHtml(l,compact=false){if(!l.price)return"";return `<div class="lodging-price${compact?" lodging-price--compact":""}"><span class="lodging-price-status is-booked">已预订</span><strong><small>¥</small>${l.price.amount}</strong><span class="lodging-price-basis">${l.price.basis}</span></div>`}function linksHtml(l,compact=false){if(!l.bookingLinks.length)return"";return `<div class="lodging-booking-links${compact?" lodging-booking-links--compact":""}">${l.bookingLinks.map(x=>`<a class="lodging-booking-link" href="${x.url}" target="_blank" rel="noopener noreferrer">${x.provider}<span aria-hidden="true">↗</span></a>`).join("")}</div>`}
function formatMoney(amount){return Number(amount).toLocaleString("zh-CN")}
function flightCardHtml(f){return `<article class="flight-card"><div class="flight-top"><div><p>${f.direction}</p><small>${f.airline}</small></div><span class="flight-no">${f.flightNo}</span></div><div class="flight-route"><div class="airport"><strong>${f.from.code}</strong><span>${f.from.city}</span><small>${f.from.time}</small></div><span class="plane"><b>✈</b><small>${f.duration}</small></span><div class="airport"><strong>${f.to.code}</strong><span>${f.to.city}</span><small>${f.to.time}</small></div></div><div class="flight-fare"><span>${f.price.basis}</span><strong><small>¥</small>${formatMoney(f.price.amount)}</strong>${f.price.breakdown?`<small>${f.price.breakdown}</small>`:""}</div><p class="flight-note">${f.note}</p></article>`}
function flightGroupsHtml(){return travelerGroups.map(g=>{const groupFlights=flights.filter(f=>f.group===g.group),perPerson=groupFlights.reduce((sum,f)=>sum+f.price.amount,0),groupTotal=perPerson*g.travelers;return `<section class="flight-group" aria-label="${g.group} 航班"><header class="flight-group-heading"><div><span>${g.group}</span><strong>往返 ¥${formatMoney(perPerson)} / 人</strong></div><small>${g.origin} · ${g.travelers} 人合计 ¥${formatMoney(groupTotal)}</small></header><div class="flight-group-list">${groupFlights.map(flightCardHtml).join("")}</div></section>`}).join("")}
function rentalCardHtml(r){return `<article class="rental-card focus-map" data-place="${r.place}"><header class="rental-heading"><div><span class="chip">${r.provider}</span><h3>${r.vehicle}</h3></div><span class="rental-status">${r.status}</span></header><div class="rental-specs">${r.specs.map(s=>`<span>${s}</span>`).join("")}<span>${r.duration}</span></div><div class="rental-schedule"><section><span>取车</span><strong>${r.pickup.date} · ${r.pickup.time}</strong><small>${r.pickup.store}<br>${r.pickup.location}</small></section><section><span>还车</span><strong>${r.returnTrip.date} · ${r.returnTrip.time}</strong><small>${r.returnTrip.store}<br>${r.returnTrip.location}</small></section></div><div class="rental-payment"><span>已支付总计</span><strong><small>¥</small>${r.price.total}</strong></div><div class="rental-breakdown">${r.price.breakdown.map(x=>`<span>${x.label}<strong>${x.amount.startsWith("-")?"-¥":"¥"}${x.amount.replace("-","")}</strong></span>`).join("")}</div><aside class="rental-alert"><strong>必须调整</strong><p>${r.warning}</p></aside><button class="link-button" type="button"><span>在地图查看取还车点</span><span class="link-button-arrow" aria-hidden="true">→</span></button></article>`}
function html(){flightSummary.innerHTML=flightGroupsHtml();tripCalendar.innerHTML=calendar.map(d=>`<article class="calendar-day calendar-day--${[3,4].includes(d.date)?"weekend":"holiday"}"><div class="calendar-day-top"><span>${d.weekday}</span><i>假</i></div><strong>${d.date}</strong><span class="calendar-day-label">${[3,4].includes(d.date)?"周末":"国庆假期"}</span><small>${d.note}</small></article>`).join("");routeFlow.innerHTML=days.map(d=>`<article class="flow-item"><span class="flow-date">${d.date.split(" ")[0]}</span><div><strong>${d.title}</strong><p>${d.drive} · 住 ${d.stay}</p></div></article>`).join("");dayList.innerHTML=days.map((d,i)=>`<article class="day-card"><div class="card-top"><span class="date-badge">${d.date}</span><span class="date-badge drive-badge">${d.drive}</span></div><h3>${d.title}</h3><ul>${d.activities.map(a=>`<li>${a}</li>`).join("")}</ul><p class="stay">住宿：${d.stay}</p><button class="link-button" data-day="${i}">在地图查看路线 →</button></article>`).join("");lodgingList.innerHTML=lodgings.map(l=>`<article class="lodging-card focus-map" data-place="${l.place}"><div class="lodging-meta"><span class="chip">${l.city}</span><span class="chip">${l.dates} · ${l.nights}</span></div><h3>${l.name}</h3>${priceHtml(l)}<p class="lodging-detail"><strong>${l.room}</strong><br>${l.checkTimes}</p><p>${l.note}</p>${linksHtml(l)}</article>`).join("");spotList.innerHTML=spots.map(s=>`<article class="spot-card focus-map" data-place="${s.place}">${s.image?`<div class="spot-images"><img loading="lazy" referrerpolicy="no-referrer" src="${s.image}" alt="${s.name}参考图" onerror="this.hidden=true"></div>`:""}<div class="spot-copy"><span class="chip">${s.tag}</span><h3>${s.name}</h3><p>${s.note}</p></div></article>`).join("");drivingList.innerHTML=driving.map(d=>`<article class="driving-card"><span class="chip">${d.tag}</span><h3>${d.name}</h3><p>${d.note}</p></article>`).join("");prepList.innerHTML=prep.map(g=>`<article class="prep-group"><h3>${g.group}</h3><ul>${g.items.map(i=>`<li>${i}</li>`).join("")}</ul></article>`).join("")}html();
drivingList.insertAdjacentHTML("afterbegin",rentalCardHtml(carRental));
const tabs=[...document.querySelectorAll(".tab-button")];function activate(b,f=false){tabs.forEach(t=>{const on=t===b;t.classList.toggle("active",on);t.setAttribute("aria-selected",on);t.tabIndex=on?0:-1});document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===b.dataset.view));if(f)b.focus()}tabs.forEach(b=>b.onclick=()=>activate(b));document.querySelector(".tabs").onkeydown=e=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(e.key))return;e.preventDefault();let i=tabs.indexOf(document.activeElement);i=e.key==="Home"?0:e.key==="End"?tabs.length-1:e.key==="ArrowRight"?(i+1)%tabs.length:(i-1+tabs.length)%tabs.length;activate(tabs[i],true)};
const map=L.map("map",{zoomControl:false});L.control.zoom({position:"bottomleft"}).addTo(map);L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",{attribution:"Tiles © Esri · Route © OSM",maxZoom:17}).addTo(map);const layers={fallback:L.layerGroup().addTo(map),route:L.layerGroup().addTo(map),hotels:L.layerGroup().addTo(map),spots:L.layerGroup().addTo(map),flights:L.layerGroup(),airports:L.layerGroup()},lines=[],markers=new Map();days.forEach((d,i)=>{const c=d.route.map(k=>[places[k].lat,places[k].lng]),l=L.polyline(c,{color:colors[i],weight:4,dashArray:"9 9"}).addTo(layers.fallback);lines.push(l);L.tooltip({permanent:true,className:"map-label"}).setLatLng(c[Math.floor(c.length/2)]).setContent(d.date.split(" ")[0]).addTo(map)});lodgings.forEach(l=>{const p=places[l.place],m=L.marker([p.lat,p.lng],{icon:L.divIcon({className:"hotel-icon",html:"住",iconSize:[28,28]})}).bindPopup(`<strong>${l.name}</strong><br>${l.dates} · ${l.nights}${priceHtml(l,true)}<br>${l.room}<br>${l.note}${linksHtml(l,true)}`).addTo(layers.hotels);markers.set(l.place,m)});spots.forEach(s=>{const p=places[s.place],m=L.marker([p.lat,p.lng],{icon:L.divIcon({className:"spot-icon",html:"景",iconSize:[27,27]})}).bindPopup(`<strong>${s.name}</strong><br>${s.note}`).addTo(layers.spots);markers.set(s.place,m)});const bounds=L.latLngBounds(days.flatMap(d=>d.route.map(k=>[places[k].lat,places[k].lng])));map.fitBounds(bounds.pad(.08));mapLegend.innerHTML=days.map((d,i)=>`<button class="legend-item" data-day="${i}"><span class="legend-swatch" style="background:${colors[i]}"></span>${d.date.split(" ")[0]} ${d.title}</button>`).join("");document.querySelectorAll("[data-day]").forEach(b=>b.onclick=()=>map.fitBounds(lines[+b.dataset.day].getBounds().pad(.25)));document.querySelectorAll(".focus-map").forEach(c=>c.onclick=()=>{const p=places[c.dataset.place];map.setView([p.lat,p.lng],11);markers.get(c.dataset.place)?.openPopup()});fitRouteButton.onclick=()=>map.fitBounds(bounds.pad(.08));function toggle(id,layer){const b=document.querySelector(id);b.onclick=()=>{const on=map.hasLayer(layer);on?map.removeLayer(layer):layer.addTo(map);b.setAttribute("aria-pressed",String(!on))}}toggle("#toggleLodgingButton",layers.hotels);toggle("#toggleSpotsButton",layers.spots);
const rentalLayer=L.layerGroup().addTo(map),rentalPlace=places[carRental.place],rentalMarker=L.marker([rentalPlace.lat,rentalPlace.lng],{icon:L.divIcon({className:"rental-icon",html:"车",iconSize:[30,30]})}).bindPopup(`<strong>${carRental.provider} · ${carRental.vehicle}</strong><br>取车：${carRental.pickup.date} ${carRental.pickup.time}<br>还车：${carRental.returnTrip.date} ${carRental.returnTrip.time}<br>${carRental.pickup.location}<br><b>已支付 ¥${carRental.price.total}</b><br><small>${carRental.warning}</small>`).addTo(rentalLayer);markers.set(carRental.place,rentalMarker);toggle("#toggleRentalButton",rentalLayer);
toggleFlightsButton.onclick=()=>{const on=map.hasLayer(layers.flights);if(!on){if(!layers.airports.getLayers().length)Object.entries(airports).forEach(([c,a])=>L.marker([a.lat,a.lng],{icon:L.divIcon({className:"airport-map-icon",html:`✈ ${c}`,iconSize:[58,30]})}).bindPopup(`<strong>${c} · ${a.name}</strong>`).addTo(layers.airports));if(!layers.flights.getLayers().length)flights.forEach(f=>L.polyline([[airports[f.from.code].lat,airports[f.from.code].lng],[airports[f.to.code].lat,airports[f.to.code].lng]],{color:"#35778c",dashArray:"11 8"}).bindPopup(`<strong>${f.group} · ${f.direction}</strong><br>${f.airline} ${f.flightNo}<br>${f.from.code} ${f.from.time} → ${f.to.code} ${f.to.time}<br>每人 ¥${formatMoney(f.price.amount)}`).addTo(layers.flights));layers.flights.addTo(map);layers.airports.addTo(map);map.fitBounds(L.latLngBounds(Object.values(airports).map(a=>[a.lat,a.lng])))}else{map.removeLayer(layers.flights);map.removeLayer(layers.airports);map.fitBounds(bounds.pad(.08))}toggleFlightsButton.setAttribute("aria-pressed",String(!on))};
loadRoutesButton.onclick=async()=>{loadRoutesButton.disabled=true;layers.route.clearLayers();let ok=0;for(let i=0;i<days.length;i++)try{const ps=days[i].route.map(k=>places[k]),path=ps.map(p=>`${p.lng},${p.lat}`).join(";"),res=await fetch(`https://router.project-osrm.org/route/v1/driving/${path}?overview=full&geometries=geojson`),data=await res.json();L.geoJSON(data.routes[0].geometry,{style:{color:colors[i],weight:5}}).addTo(layers.route);ok++}catch{}loadRoutesButton.disabled=false;loadRoutesButton.textContent="重新加载路线";mapStatus.textContent=`已加载 ${ok}/${days.length} 天驾车路线，其余保留虚线`};
